import Haha from "@/components/cards/haha";
import TopBar from "@/components/shared/top-bar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sync",
  description: "Generated by create next app",
};

export default function FeedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <TopBar />
      <div className="flex space-x-4">
        {children}
        <div className="flex-1">
          <Haha />
        </div>
        <div className="bg-card rounded-md w-20">
          {/* <Haha /> */}
        </div>
      </div>
    </section>
  );
}
