import Haha from "@/components/cards/haha";
import TopBar from "@/components/shared/top-bar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sync",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <TopBar />
      <div className="flex space-x-3">
        {children}
        <div className="flex-1 border">
          <Haha />
        </div>
      </div>
    </section>
  );
}
