import QueryClientProvder from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import SessionProvider from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";
import React from "react";
import LeftSideBar from "@/components/shared/left-sidebar";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { EdgeStoreProvider } from "@/lib/edgestore";
import TopBar from "@/components/shared/top-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sync",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <QueryClientProvder>
              <EdgeStoreProvider>
                <main className="container relative flex h-auto justify-between px-0">
                  <LeftSideBar />
                  <div className="flex-1 pr-4">
                    <TopBar />
                    {children}
                  </div>
                </main>
              </EdgeStoreProvider>
              <Toaster richColors />
            </QueryClientProvder>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
